### ISSUE TITLE
Request: Close all MenuItems that are expanded when clicking a MenuItem with href

### ISSUE THREAD

**Issue by nunonux** [amirkian007/vue-awesome-sidebar#11]
Hello,

I think it would be great if on clicking a MenuItem with a href, one to go to a route, all the others MenuItems with children that are expanded (showing the children), could close or compress.

**Comment by nunonux** [comment]
Compress like the autonym of expanded.

**Comment by amirkian007** [comment]
@nunonux 
Hello again , i add the option and released a new version(1.2.3) ,all you have to to is to add the `closeOpenMenuOnHrefPush` option to the component ! if there is anything else please let me know.
