### ISSUE TITLE
How can I handle the event closeOnClickOutSide

### ISSUE THREAD

**Issue by AndreyKachanov** [amirkian007/vue-awesome-sidebar#12]
How can I handle the event closeOnClickOutSide?

**Comment by amirkian007** [comment]
@AndreyKachanov 
hi , `closeOnClickOutSide` is a prop that if set to `true` closes(collapse) the sidebar when the outside is clicked, it does not emit any events though ... but you can use `@update:collapsed(isCollapsed)` event to listen to collapsed value to detect when a menu is collapsed or you can set a watcher on collapsed value, here are some examples with composition api :
```html
<template>
  <VueAwesomeSideBar
      v-model:miniMenu="miniMenu"
      v-model:collapsed="collapsed"
      @update:collapsed="handelCollapse"
      :menu="testMenu"
      vueRouterEnabel
    ></VueAwesomeSideBar>
</template>

<script setup>
import { ref, watch } from 'vue'

const collapsed = ref(false)
const miniMenu = ref(false)

// method 1
function handelCollapse(value){
if(!value){
  console.log("menu is closed")
}
}

//method 2
watch(collapsed , (newValue, prevValue) => {
if(!newValue){
  console.log("menu is closed")
}
})

const testMenu = [
  {
    name: 'Getting Started',
    icon: { text: 'home' , class: 'material-icons-outlined' },
    }
   ]
  </script>
```
does this solve your problem ?

**Comment by AndreyKachanov** [comment]
> @AndreyKachanov hi , `closeOnClickOutSide` is a prop that if set to `true` closes(collapse) the sidebar when the outside is clicked, it does not emit any events though ... but you can use `@update:collapsed(isCollapsed)` event to listen to collapsed value to detect when a menu is collapsed or you can set a watcher on collapsed value, here are some examples with composition api :
> 
> ```
> <template>
>   <VueAwesomeSideBar
>       v-model:miniMenu="miniMenu"
>       v-model:collapsed="collapsed"
>       @update:collapsed="handelCollapse"
>       :menu="testMenu"
>       vueRouterEnabel
>     ></VueAwesomeSideBar>
> </template>
> 
> <script setup>
> import { ref, watch } from 'vue'
> 
> const collapsed = ref(false)
> const miniMenu = ref(false)
> 
> // method 1
> function handelCollapse(value){
> if(!value){
>   console.log("menu is closed")
> }
> }
> 
> //method 2
> watch(collapsed , (newValue, prevValue) => {
> if(!newValue){
>   console.log("menu is closed")
> }
> })
> 
> const testMenu = [
>   {
>     name: 'Getting Started',
>     icon: { text: 'home' , class: 'material-icons-outlined' },
>     }
>    ]
>   </script>
> ```
> 
> does this solve your problem ?

No, I want to set variable collapsed=true after clicking "closeOnClickOutSide", but I don't understand how to do it right

**Comment by AndreyKachanov** [comment]
I have button with @click="collapsed = !collapsed". But if i click "closeOnClickOutSide", variable collapsed not  does not switch to true

**Comment by AndreyKachanov** [comment]
I solved the problem, thanks.
```
        handelCollapse(value) {
            if (value === true) {
                this.collapsed = true;
            }
        }
```
