### ISSUE TITLE
[Idea] Prop for for one open menu at a time

### ISSUE THREAD

**Issue by Bartek20** [amirkian007/vue-awesome-sidebar#14]
In my opinion, a nice addition would be the ability to specify that only one menu can be expanded at a time (I mean the values in the "children" parameter).
For example, on this project's documentation page:
When the "Styling" menu is expanded, the "example 1" menu collapses and vice versa

**Comment by amirkian007** [comment]
@Bartek20 
Hi, i think what you are looking for is the same thing in #11 ?

**Comment by amirkian007** [comment]
@Bartek20  well not exactly the same thing because that one is on router push , i will add one with out router push . it will be done in a week or two , if you have any suggestions for the prop name please let me know .
