### ISSUE TITLE
it didn't display with vue 3x pinia

### ISSUE THREAD

**Issue by Thuytran79** [amirkian007/vue-awesome-sidebar#19]
I installed and use like example, but it  didn't display.
I use vue 3.2
can you help me?

**Comment by amirkian007** [comment]
@Thuytran79 Hi
can you give me a code example of how you used the component ?  did you install it correctly ?

**Comment by Thuytran79** [comment]
Thanks for your answer!
I using like that.

![image](https://github.com/amirkian007/vue-awesome-sidebar/assets/86605918/8968cebc-80c0-4af1-bc91-8291ad5bfde5)

![image](https://github.com/amirkian007/vue-awesome-sidebar/assets/86605918/210f27ff-4a6d-435e-8101-4bd8b9fcdf12)

**Comment by amirkian007** [comment]
@Thuytran79 
i found the problem ,it seems like you are not importing it correctly, the default export for this package is the install plugin which is to install the component globally . when you want to use the component locally you have to use named imports like this : 
```html
<template>
  <VueAwesomeSideBar
      v-model:miniMenu="miniMenu"
      v-model:collapsed="collapsed"
      :menu="testMenu"
      vueRouterEnabel
    ></VueAwesomeSideBar>
</template>


<script setup>
import { ref } from 'vue'
import {VueAwesomeSideBar} from 'vue-awesome-sidebar'
import 'vue-awesome-sidebar/dist/vue-awesome-sidebar.css'
// rest of the code ... 
</script>
```
MAKE SURE to capitalize the component name when importing it , let me know if it worked or not .
 this is also a typo mistake in the docs which i have to fix

**Comment by Thuytran79** [comment]
Great! It worked. Thank you!
The problem is in the capital letters.
it's working but maybe there's a type problem with import component name way.
![image](https://github.com/amirkian007/vue-awesome-sidebar/assets/86605918/1b8867cd-255d-47f9-9e53-a65d1e8b787a)

**Comment by amirkian007** [comment]
@Thuytran79 
yeah i need to change to export in the package for that type error
for now you can ignore the error by using :
```ts
// @ts-ignore  
import {VueAwesomeSideBar} from 'vue-awesome-sidebar'
```

**Comment by Thuytran79** [comment]
Thank you!
