### ISSUE TITLE
Providing an options that indicates whether open a non-leaf node.

### ISSUE THREAD

**Issue by zsh2401** [amirkian007/vue-awesome-sidebar#3]
Just like what the title described, I suggest that there should be an option that enables developer to prevent vas from opening path when user clicked a menu item, which has children, with an aim to just expand it.

**Comment by amirkian007** [comment]
@zsh2401 you mean like adding a disable option to menu item ? which locks the menu item and adds disable styles ?

**Comment by zsh2401** [comment]
When I expanding a menu that has children, I wish that it will not navigate to some one of child of that menu.

**Comment by zsh2401** [comment]
The solution is not passing herf to non-leaf node.
