### ISSUE TITLE
Request: can you please share the code for the live demo website?

### ISSUE THREAD

**Issue by ta-soft** [amirkian007/vue-awesome-sidebar#6]
I don't see the code for the live demo website, and I think the div structure there (bar at the top with the burger icon) is exactly what most people would be looking for, so it could be very useful to have it here in git too. Would you mind sharing that?

**Comment by amirkian007** [comment]
@ta-soft Hi, the code for live demo is a bit messy, good luck
[https://github.com/amirkian007/vasmenu](https://github.com/amirkian007/vasmenu)

**Comment by ta-soft** [comment]
> @ta-soft Hi, the code for live demo is a bit messy, good luck
> https://github.com/amirkian007/vasmenu

ah, I see, you used vuetify. Thanks for sharing, I think it will help anyway.
