### ISSUE TITLE
menu attribute "width" doesn't seem to work

### ISSUE THREAD

**Issue by ta-soft** [amirkian007/vue-awesome-sidebar#7]
If you include it (see example below, modified in this project to test), it will simply ignore whatever number you put there and make the menu as small as the contents of the menu.

`<Menu
    :menu="testmENU"
    v-model:miniMenu="miniMenu"
    v-model:collapsed="collapsed"
    @item-click="hanc"
    vueRouterEnabel
    dark
    width="300"
    :autoCollapse="600"
    menuType="fully"
  >
  </Menu>`

**Comment by amirkian007** [comment]
@ta-soft hi again
in the example you provided it seems that you didn't set a unit for the width
Like `width:="300px"`
Try setting a unit for the with and pass it to menu as a string and let men know if it works or not

**Comment by ta-soft** [comment]
> @ta-soft hi again
> in the example you provided it seems that you didn't set a unit for the width
> Like this `width="300px"`.
> Try setting a unit for the with and pass it to menu as a string and let men know if it works or not

goodness me, I could SWEAR I had tried with and without "px" - my apologies, it indeed works once you use "px".
